### ISSUE TITLE
Enable only for "post" post_type

### ISSUE THREAD

**Issue by gelform** [jmslbam/wp-post-url-prefixer#1]
Great plugin! However, it applies the change to all post types, which breaks existing custom post types.

I change 

`function wp_pup_register_post_type_args( $args ) {`

to 

`function wp_pup_register_post_type_args( $args, $post_type ) {`

And added 

```
if ( $post_type !== 'post' ) {
	return $args;
}
```

To the beginning of that function. This makes sure the change is only added for the `post` post_type.

**Comment by jmslbam** [comment]
Hi Corey, thank you for the feedback and fix!

Just had a new born so was a bit slow with the response.

I have committed your fix and it's now in the main branch.

Ciao!

**Comment by gelform** [comment]
Congrats!
